steps:
  - template: ../steps/install-nodejs.yml
  - template: ../steps/install-dependencies.yml
  - script: yarn check-deps
    displayName: "Check dependencies"
  - script: yarn check-types
    displayName: "Check JSDoc types"
  - script: yarn lint
    displayName: "Lint code"
  - script: yarn lint-docs
    displayName: "Lint docs"
  - script: yarn spellcheck
    displayName: "Spellcheck"
  - script: yarn && echo "Listing changed files:" && git diff --name-only --exit-code && echo "No files changed during lint."
    displayName: "Check file changes"
  - script: yarn lint-changelog
    displayName: "Lint changelog"
