[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.22.10"
[[headers]]
  for = "/worker.js"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'"
