blank_issues_enabled: true
contact_links:
  - name: Issue with experimental CLI
    url: https://github.com/prettier/prettier-cli/issues
    about: The experimental CLI currently lives in a separate repo, open an issue there instead.
  - name: ğŸ¤” Support question
    url: https://stackoverflow.com/questions/ask?tags=prettier
    about: Issues are dedicated to development purposes. If you have questions, please use Stack Overflow.
  - name: ğŸ“ Help with Visual Studio Code extension for Prettier
    url: https://github.com/prettier/prettier-vscode/issues
    about: Bugs and feature requests for the Visual Studio Code extension for Prettier
