name: Bundler_Friendly

on:
  schedule:
    # “At 00:00 on Sunday.” https://crontab.guru/#0_0_*_*_SUN
    - cron: "0 0 * * SUN"
  pull_request:
    paths:
      - "scripts/tools/bundle-test/**"
      # This workflow file
      - ".github/workflows/bundler-friendly.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name != 'schedule' || github.repository == 'prettier/prettier'
    name: Build
    uses: ./.github/workflows/_build.yml

  webpack:
    if: github.event_name != 'schedule' || github.repository == 'prettier/prettier'
    name: Bundle Prettier with webpack
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Download Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: dist

      - name: Install Dependencies
        run: yarn install --immutable
        working-directory: scripts/tools/bundle-test

      - name: Test
        run: yarn test
        working-directory: scripts/tools/bundle-test
