name: Mark Issue Duplicate

on:
  issue_comment:
    types: [created]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - name: mark-duplicate
        uses: actions-cool/issues-helper@1.x
        with:
          actions: "mark-duplicate"
          token: ${{ secrets.GITHUB_TOKEN }}
          duplicate-labels: "type:duplicate"
          allow-permissions: "admin, write"
          close-issue: true

