name: Mark Issue Duplicate

on:
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && startsWith(github.event.comment.body, 'Duplicate of ') }}
    steps:
      - uses: actions-cool/issues-helper@v3.5.2
        with:
          actions: "mark-duplicate"
          token: ${{ secrets.GITHUB_TOKEN }}
          duplicate-labels: "type:duplicate"
          close-issue: true
