name: Prevent File change

on:
  pull_request:
    paths:
      - "website/data/users.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prevent-add-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Prevent file change
        uses: xalvarez/prevent-file-change-action@v1.3.2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: website/data/users.yml
