name: Prevent File change

on:
  pull_request_target:
    paths:
      - "website/data/users.yml"

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prevent-add-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prevent file change
        uses: xalvarez/prevent-file-change-action@v1.9.1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: website/data/users.yml
