name: "Support requests"

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: "type:question"
          issue-comment: >
            :wave: @{issue-author}, we use the issue tracker exclusively for development purposes.
            For questions, please use [Stack Overflow](https://stackoverflow.com/questions/ask?tags=prettier).
